server:
  port: 8086

spring:
  application:
    name: notify-service
  profiles:
    active: dev

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info

# 日志配置
logging:
  level:
    com.sia.notify: DEBUG
